# Generated by Django 4.0.4 on 2022-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdetails',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='al_stream',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='certificate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='dob',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='home_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='mobile_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='ol_result',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='postalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='subject1',
            field=models.CharField(choices=[('Com Maths', 'Com Maths'), ('chem', 'chem'), ('P6', 'P6')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='subject2',
            field=models.CharField(choices=[('Com Maths', 'Com Maths'), ('chem', 'chem'), ('P6', 'P6')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='subject3',
            field=models.CharField(choices=[('Com Maths', 'Com Maths'), ('chem', 'chem'), ('P6', 'P6')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='volunteering',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
