# Generated by Django 4.0.4 on 2022-05-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0003_media_portfolio_skill_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
