# Generated by Django 4.0.4 on 2022-05-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdetails',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='project',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='cvdetails',
            name='volunteering',
        ),
    ]
