# Generated by Django 4.0.4 on 2022-05-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0005_rename_dob_cvdetails_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdetails',
            name='nic',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
