# Generated by Django 4.0.4 on 2022-05-19 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0006_cvdetails_nic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdetails',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
