# Generated by Django 4.0.4 on 2022-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0007_cvdetails_body_cvdetails_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvdetails',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cvdetails',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
