# Generated by Django 4.0.4 on 2022-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgenr', '0010_delete_media_delete_portfolio_delete_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvdetails',
            name='skill',
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cvdetails',
            name='skill6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
